org: PAS
space: PAS-CLAIMS-DEV
space-developer:
  ldap_users: []
  users:
  - kusuma.cherukuri@csaa.com
  - kevin.norton@csaa.com
  - swaminathan.viswanathan@csaa.com
  - manoj.pokharel@csaa.com
  - jacky.zhong@csaa.com
  - saravanakumar.c@csaa.com
  - sushma.koni@csaa.com
  - palaniappan.subbiah@csaa.com
  - vigneshwar.maruthavanan@csaa.com
  - aiga.romane@csaa.com
  - arturs.vinogradovs@csaa.com
  - sreedevi.katari@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - pasauditor
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
