org: ds
space: claims-rideshare-prod
space-developer:
  ldap_users: []
  users:
  - ci-rideshare
  - john.dee@csaa.com
  - adam.mott@csaa.com
  - scott.paige@csaa.com
  - pawel.bardzinski@csaa.com
  - brant.stuns@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - vikram.ravindhran@csaa.com
  - amit.mishra@csaa.com
  - vasanth.jayaraman@csaa.com
  - john.beaty@csaa.com
  - chandra.sekhar.ganta@csaa.com
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
