org: ds
space: ds_web-prod
space-developer:
  ldap_users: []
  users:
  - adam.mott@csaa.com
  - michael.e.kelly@csaa.com
  - dhirender.kumar@csaa.com
  - samar.kumar@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - adam.mott@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
