org: ds
space: quote-dev
space-developer:
  ldap_users: []
  users:
  - pbardzinski
  - swolfe
  - bstuns
  - dkumar
  - bsnodgrass
  - alee
  - ci-quote-2
  - jdee
  - jhirsch
  - lita-concourse
  - admin
  - amott
  - bstilwell
  - tbenson
  - jutter
  - kcampos
  - jnimlos
  - rmedina
  - spaige
  - bmallick
  - kkanagaraj
  - hmahey
  - dsaravanmuthu
  - nnair
  - esubbaiyan
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - lita-concourse
  - admin
  - amott
  - jnimlos
  - jdee
  - pbardzinski
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - jutter
  - lita-concourse
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
