org: integrated_services
space: shub-dev
space-developer:
  ldap_users: []
  users:
  - deviprasad.gangina@csaa.com
  - abhijith.komalachery@csaa.com
  - dan.thompson@csaa.com
  - sankaranarayanan.v@csaa.com
  - venkata.damera@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - dan.thompson@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
