org: PAS
space: DXP TEST
space-developer:
  ldap_users: []
  users:
  - kusuma.cherukuri@csaa.com
  - kevin.norton@csaa.com
  - swaminathan.viswanathan@csaa.com
  - manoj.pokharel@csaa.com
  - saravanakumar.c@csaa.com
  - sushma.koni@csaa.com
  - palaniappan.subbiah@csaa.com
  - vigneshwar.maruthavanan@csaa.com
  - arturs.vinogradovs@csaa.com
  - samantha.stovall@csaa.com
  - ryan.mccullough@csaa.com
  - erik.kriel@csaa.com
  - darren.butler@csaa.com
  - ci-dxp
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - pasauditor
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
