org: ds
space: mypolicy-da-evalue2
space-developer:
  ldap_users: []
  users:
  - swolfe
  - alee
  - kpatel
  - kperry
  - kcampos
  - jdee
  - rkumar
  - lita-concourse
  - spaige
  - dgudima
  - jutter
  - amott
  - jnimlos
  - bstuns
  - dkumar
  - ci-mypolicy-da
  - pbardzinski
  - tbenson
  - bmallick
  - rmedina
  - hmahey
  - amcwatters
  - esubbaiyan
  - dsaravanmuthu
  - jhirsch
  - vjayakar
  - garogia
  - kkanagaraj
  - apillai
  - abhaskarakurup
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - jdee
  - lita-concourse
  - jnimlos
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
