org: ds
space: mypolicy-da-evalue2
space-developer:
  ldap_users: []
  users:
  - swolfe
  - alee
  - kpatel
  - kperry
  - kyle.campos@csaa.com
  - john.dee@csaa.com
  - rkumar
  - lita-concourse
  - spaige
  - dgudima
  - jon.utter@csaa.com
  - adam.mott@csaa.com
  - bstuns
  - dkumar
  - ci-mypolicy-da
  - pbardzinski
  - tbenson
  - bmallick
  - ryan.medina@csaa.com
  - hmahey
  - amcwatters
  - esubbaiyan
  - dsaravanmuthu
  - vjayakar
  - garogia
  - kkanagaraj
  - apillai
  - abhaskarakurup
  - skumar
  - nnair
  - dilipkumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - john.dee@csaa.com
  - lita-concourse
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
