org: ds
space: ezpay-prod
space-developer:
  ldap_users: []
  users:
  - ci-mypolicy-da
  - scott.paige@csaa.com
  - adam.mott@csaa.com
  - brant.stuns@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - samar.kumar@csaa.com
  - jason.mcneill@csaa.com
  - ci-ezpay
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - dumitru.gudima@csaa.com
  - birabrat.mallick@csaa.com
  - dhirender.kumar@csaa.com
  - samar.kumar@csaa.com
  - karthik.kanagaraj@csaa.com
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 0
instance-memory-limit: 0
total-routes: 0
total-services: 0
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
total_private_domains: 0
total_reserved_route_ports: 0
total_service_keys: 0
app_instance_limit: 0
isolation_segment: ""
named-security-groups: []
