org: ds
space: iportal-prod
space-developer:
  ldap_users: []
  users:
  - ci-iportal
  - john.dee@csaa.com
  - admin
  - adam.mott@csaa.com
  - kyle.campos@csaa.com
  - dgudima
  - dhirender.kumar@csaa.com
  - spaige
  - skumar
  - karthik.kanagaraj@csaa.com
  - pawel.bardzinski@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
