org: ds
space: mypolicy-da-mo
space-developer:
  ldap_users: []
  users:
  - kcampos
  - kpatel
  - kperry
  - ci-mypolicy-da
  - rkumar
  - dgudima
  - chitrak
  - spaige
  - bmallick
  - rjeffery
  - bstuns
  - rmedina
  - hmahey
  - jnimlos
  - amcwatters
  - esubbaiyan
  - dsaravanmuthu
  - vjayakar
  - garogia
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - jnimlos
  - kcampos
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
