org: ds
space: mypolicy-da-mo
space-developer:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  - kpatel
  - kperry
  - ci-mypolicy-da
  - rkumar
  - dgudima
  - spaige
  - bmallick
  - bstuns
  - dkumar
  - ryan.medina@csaa.com
  - hmahey
  - amcwatters
  - esubbaiyan
  - dsaravanmuthu
  - vjayakar
  - garogia
  - kkanagaraj
  - apillai
  - abhaskarakurup
  - skumar
  - nnair
  - dilipkumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
