org: ds
space: mypolicy-da-test
space-developer:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  - kpatel
  - kperry
  - ci-mypolicy-da
  - rkumar
  - dgudima
  - spaige
  - birabrat.mallick@csaa.com
  - bstuns
  - dkumar
  - hmahey  
  - adam.mott@csaa.com
  - ryan.medina@csaa.com
  - amcwatters
  - esubbaiyan
  - anthony.lee@csaa.com
  - dsaravanmuthu
  - vjayakar
  - kkanagaraj
  - anu.pillai@csaa.com
  - anooj.bhaskarakurup@csaa.com
  - skumar
  - nnair
  - dilipkumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
