org: ds
space: mypolicy-da-concourse
space-developer:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - tbenson
  - anthony.lee@csaa.com
  - spaige
  - jon.utter@csaa.com
  - lita-concourse
  - ci-mypolicy-da
  - dgudima
  - bstuns
  - dhirender.kumar@csaa.com
  - kperry
  - elumala.subbaiyan@csaa.com
  - skumar
  - harsh.mahey@csaa.com
  - divya.saravanamuthu@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - kpatel
  - kperry
  - rkumar
  - birabrat.mallick@csaa.com
  - ryan.medina@csaa.com
  - amcwatters
  - elumala.subbaiyan@csaa.com
  - vjayakar
  - george.arogia@csaa.com
  - karthik.kanagaraj@csaa.com
  - anu.pillai@csaa.com
  - anooj.bhaskarakurup@csaa.com
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
