org: ds
space: envoy-dev
space-developer:
  ldap_users: []
  users:
  - pawel.bardzinski@csaa.com
  - swolfe
  - bstuns
  - dkumar
  - bsnodgrass
  - anthony.lee@csaa.com
  - ci-quote-2
  - john.dee@csaa.com
  - lita-concourse
  - admin
  - adam.mott@csaa.com
  - tbenson
  - jon.utter@csaa.com
  - kyle.campos@csaa.com
  - ryan.medina@csaa.com
  - spaige
  - birabrat.mallick@csaa.com
  - kkanagaraj
  - hmahey
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - lita-concourse
  - admin
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
