org: ds
space: quote-prod
space-developer:
  ldap_users: []
  users:
  - ci-quote-2
  - adam.mott@csaa.com
  - kyle.campos@csaa.com
  - john.dee@csaa.com
  - bstuns
  - dhirender.kumar@csaa.com
  - admin
  - brian.w.snodgrass@csaa.com
  - karthik.kanagaraj@csaa.com
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - admin
  - adam.mott@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - ryan.medina@csaa.com
  - swolfe
  - bstuns
  - divya.saravanamuthu@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
