org: ds
space: quote-prod
space-developer:
  ldap_users: []
  users:
  - ci-quote-2
  - amott
  - kcampos
  - jdee
  - bstuns
  - dkumar
  - admin
  - bsnodgrass
  - kkanagaraj
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - admin
  - amott
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - jnimlos
  - jhirsch
  - rmedina
  - swolfe
  - bstuns
  - bstilwell
  - dsaravanmuthu
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
