org: ds
space: quote-cert
space-developer:
  ldap_users: []
  users:
  - admin
  - ci-quote-2
  - kyle.campos@csaa.com
  - bstuns
  - dhirender.kumar@csaa.com
  - ryan.medina@csaa.com
  - brian.w.snodgrass@csaa.com
  - birabrat.mallick@csaa.com
  - karthik.kanagaraj@csaa.com
  - spaige
  - harsh.mahey@csaa.com
  - divya.saravanamuthu@csaa.com
  - nnair
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - admin
  - kyle.campos@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
