org: ds
space: ubi_mobile-test
space-developer:
  ldap_users: []
  users:
  - pawel.bardzinski@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - kyle.campos@csaa.com
  - vikram.ravindhran@csaa.com
  - amit.mishra@csaa.com
  - johri.dhanotra@csaa.com
  - pitchi.babu.sayani@csaa.com
  - swapnil.murmurwar@csaa.com
  - ci-ubi_mobile
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
