org: ds
space: mpc-dev
space-developer:
  ldap_users: []
  users:
  - ci-mypolicy-da
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - bstuns
  - dhirender.kumar@csaa.com
  - harsh.mahey@csaa.com
  - elumala.subbaiyan@csaa.com
  - skumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - john.dee@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - john.dee@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
