org: integrated_services
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users:
  - adam.mott@csaa.com
  - kyle.campos@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - lita-concourse
  - admin
  ldap_group: ""
org-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
enable-org-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: true
enable-remove-users: true
