org: ds
space: mpc-test
space-developer:
  ldap_users: []
  users:
  - ci-mypolicy-da
  - jnimlos
  - pwagner
  - jdee
  - bstuns
  - rjeffery
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - jnimlos
  - pwagner
  - jdee
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - jdee
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
