org: ds
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users:
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - brant.stuns@csaa.com
  - lita-concourse
  - admin
  ldap_group: ""
org-auditor:
  ldap_users: []
  users:
  - dhirender.kumar@csaa.com
  - samar.kumar@csaa.com
  ldap_group: ""
enable-org-quota: true
memory-limit: 460800
instance-memory-limit: -1
total-routes: 1700
total-services: 200
paid-service-plans-allowed: true
enable-remove-users: true
