org: ds
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users:
  - adam.mott@csaa.com
  - kyle.campos@csaa.com
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - lita-concourse
  - admin
  ldap_group: ""
org-auditor:
  ldap_users: []
  users:
  - dkumar
  - skumar
  ldap_group: ""
enable-org-quota: true
memory-limit: 256000
instance-memory-limit: -1
total-routes: 1000
total-services: 100
paid-service-plans-allowed: true
enable-remove-users: true
