org: ds
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users:
  - amott
  - jnimlos
  - pwagner
  - kcampos
  - jdee
  - pbardzinski
  - lita-concourse
  - admin
  ldap_group: ""
org-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
enable-org-quota: true
memory-limit: 150000
instance-memory-limit: -1
total-routes: 1000
total-services: 100
paid-service-plans-allowed: false
enable-remove-users: true
