org: ds
spaces:
- quote-dev
- quote-prod
- quote-test
- quote-evalue
- ops_utilities-dev
- ops_utilities-prod
- ops_utilities-test
- alexa-service-dev
- quote-cert
- connect-services-prod
- mpc-dev
- connect-services-dev
- mpc-test
- mpc-prod
- ds_web-dev
- ds_web-prod
- mypolicy-club-dev
- mypolicy-club-test
- mypolicy-club-prod
- document-portal-dev
- document-portal-prod
- elastalert
- elastalert-dev
- service-broker
- iportal-dev
- iportal-test
- iportal-prod
- sonar-dev
- sonar-prod
- mypolicy-da-evalue
- mypolicy-da-evalue2
- iportal-evalue
- mypolicy-da-mo
- iportal-mo
- mypolicy-da-bf
- envoy-dev
- csaa-mobile-dev
- csaa-mobile-evalue
- csaa-mobile-perf
- iportal-bf
- qa-services-dev
- qa-services-test
- qa-services-prod
- mypolicy-da-concourse
- iportal-concourse
- claims-rideshare-dev
- claims-rideshare-test
- claims-rideshare-qa
- claims-rideshare-prod
- ops_security-dev
- common-services-dev
- common-services-test
- common-services-prod
- cccm-dev
- cccm-dev2
- cccm-e2e
- cccm-perf
- cccm-prod
- cccm-qa
- cccm-qa2
- shared-service-bf
- shared-service-dev
- shared-service-dev2
- shared-service-e2e
- shared-service-perf
- shared-service-prod
- shared-service-qa
- shared-service-qa2
- csaa-connected-driving-dev
- csaa-connected-driving-test
- csaa-connected-driving-prod
- sso-dev
- sso-test
- sso-perf
- pacer-dev
- pacer-test
- pacer-prod
- selfservice-dev
- ubi_mobile-dev
- ubi_mobile-test
- ubi_mobile-prod
- mypolicy-da-qa1
- mypolicy-da-qa2
- iportal-qa2
