org: ds
spaces:
- quote-dev
- quote-prod
- quote-test
- quote-evalue
- ops_utilities-dev
- ops_utilities-prod
- ops_utilities-test
- alexa-service-dev
- quote-cert
- connect-services-prod
- mpc-dev
- connect-services-dev
- mpc-test
- mpc-prod
- ds_web-dev
- ds_web-prod
- mypolicy-club-dev
- mypolicy-club-test
- mypolicy-club-prod
- document-portal-dev
- document-portal-prod
- elastalert
- service-broker
- iportal-dev
- iportal-test
- iportal-prod
- sonar-dev
- sonar-prod
