org: ds
space: admin-portal-perf
space-developer:
  ldap_users: []
  users:
  - pawel.bardzinski@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - brant.stuns@csaa.com
  - divya.saravanamuthu@csaa.com
  - dhirender.kumar@csaa.com
  - elumala.subbaiyan@csaa.com
  - samar.kumar@csaa.com
  - ci-admin-portal
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
