org: PAS
space: PAS DOC QA
space-developer:
  ldap_users: []
  users:
  - maija.strazda@csaa.com
  - anna.votinova@csaa.com
  - kusuma.cherukuri@csaa.com
  - kevin.norton@csaa.com
  - manoj.pokharel@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
