org: integrated_services
space: shub-perf
space-developer:
  ldap_users: []
  users:
  - dgangina
  - akomalachery
  - dthompson
  - kvemuri
  - sankaran
  - vdemera
  - vdemera
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - dthompson
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
