org: ds
space: ubi_mobile-prod
space-developer:
  ldap_users: []
  users:
  - pawel.bardzinski@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - scott.paige@csaa.com
  - brant.stuns@csaa.com
  - ci-ubi_mobile
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - vikram.ravindhran@csaa.com
  - amit.mishra@csaa.com
  - johri.dhanotra@csaa.com
  - anuj.kapil@csaa.com
  - naveenkumar.vangapelly@csaa.com
  - chandra.sekhar.ganta@csaa.com
  - pitchi.babu.sayani@csaa.com
  - arti.raj@csaa.com
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
