org: ds
space: connect-services-dev
space-developer:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  - brant.stuns@csaa.com
  - dhirender.kumar@csaa.com
  - todd.benson@csaa.com
  - lita-concourse
  - adam.mott@csaa.com
  - ci-mypolicy-da
  - john.dee@csaa.com
  - harsh.mahey@csaa.com
  - samar.kumar@csaa.com
  - todd.benson@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - harsh.mahey@csaa.com
  - lita-concourse
  - ci-mypolicy-da
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - lita-concourse
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
