org: ds
space: connect-services-dev
space-developer:
  ldap_users: []
  users:
  - chill
  - pwagner
  - kcampos
  - bstuns
  - tbenson
  - kperry
  - lita-concourse
  - amott
  - ci-mypolicy-da
  - rjeffery
  - jdee
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - chill
  - pwagner
  - lita-concourse
  - ci-mypolicy-da
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - lita-concourse
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
