org: ds
space: quote-test
space-developer:
  ldap_users: []
  users:
  - brian.w.snodgrass@csaa.com
  - ci-quote-2
  - pawel.bardzinski@csaa.com
  - ryan.medina@csaa.com
  - brant.stuns@csaa.com
  - dhirender.kumar@csaa.com
  - adam.mott@csaa.com
  - john.dee@csaa.com
  - birabrat.mallick@csaa.com
  - karthik.kanagaraj@csaa.com
  - scott.paige@csaa.com
  - harsh.mahey@csaa.com
  - divya.saravanamuthu@csaa.com
  - nidhin.nair@csaa.com
  - samar.kumar@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - ramesh.thiyagarajan@csaa.com
  - karthika.premi.subramanian@csaa.com
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
