org: ds
space: iportal-concourse
space-developer:
  ldap_users: []
  users:
  - ci-iportal
  - john.dee@csaa.com
  - pawel.bardzinski@csaa.com
  - adam.mott@csaa.com
  - kyle.campos@csaa.com
  - dgudima
  - bstuns
  - dhirender.kumar@csaa.com
  - spaige
  - anthony.lee@csaa.com
  - tbenson
  - jon.utter@csaa.com
  - elumala.subbaiyan@csaa.com
  - skumar
  - ryan.medina@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - amcwatters
  - harsh.mahey@csaa.com
  - divya.saravanamuthu@csaa.com
  - george.arogia@csaa.com
  - karthik.kanagaraj@csaa.com
  - anu.pillai@csaa.com
  - anooj.bhaskarakurup@csaa.com
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
