org: ds
space: iportal-dev
space-developer:
  ldap_users: []
  users:
  - ci-iportal
  - jdee
  - admin
  - amott
  - adam.mott@csaa.com
  - kcampos
  - dgudima
  - dkumar
  - alee
  - spaige
  - amcwatters
  - hmahey
  - dsaravanmuthu
  - garogia
  - kkanagaraj
  - apillai
  - abhaskarakurup
  - skumar
  - nnair
  - dilipkumar
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
