org: ds
space: mypolicy-da-bf
space-developer:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  - kpatel
  - kperry
  - ci-mypolicy-da
  - rkumar
  - dumitru.gudima@csaa.com
  - spaige
  - birabrat.mallick@csaa.com
  - harsh.mahey@csaa.com
  - brant.stuns@csaa.com
  - dhirender.kumar@csaa.com
  - amcwatters
  - elumala.subbaiyan@csaa.com
  - divya.saravanamuthu@csaa.com
  - vjayakar
  - george.arogia@csaa.com
  - karthik.kanagaraj@csaa.com
  - anu.pillai@csaa.com
  - anooj.bhaskarakurup@csaa.com
  - skumar
  - nnair
  - dilip.kumar.r@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - kyle.campos@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
