org: ds
space: pacer-prod
space-developer:
  ldap_users: []
  users:
  - pawel.bardzinski@csaa.com
  - brant.stuns@csaa.com
  - john.dee@csaa.com
  - lita-concourse
  - adam.mott@csaa.com
  - todd.benson@csaa.com
  - jon.utter@csaa.com
  - kyle.campos@csaa.com
  - scott.paige@csaa.com
  - ci-envoy2
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
