org: ds
space: csaa-connected-driving-prod
space-developer:
  ldap_users: []
  users:
  - john.dee@csaa.com
  - adam.mott@csaa.com
  - scott.paige@csaa.com
  - pawel.bardzinski@csaa.com
  - brant.stuns@csaa.com
  - ahil.ponarul@csaa.com
  - monica.angel@csaa.com
  - tims.thampy@csaa.com
  - pooja.kosunam@csaa.com
  - oliver.wessoniii@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users: []
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - blair.kennedy@csaa.com
  ldap_group: ""
allow-ssh: true
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
