org: PAS
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users:
  - knorton
  ldap_group: ""
org-auditor:
  ldap_users: []
  users:
  - pasauditor
  ldap_group: ""
enable-org-quota: true
memory-limit: 20480
instance-memory-limit: -1
total-routes: 1000
total-services: 100
paid-service-plans-allowed: true
enable-remove-users: true
