org: PAS
org-billingmanager:
  ldap_users: []
  users: []
  ldap_group: ""
org-manager:
  ldap_users: []
  users: []
  ldap_group: ""
org-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
enable-org-quota: false
memory-limit: 20480
instance-memory-limit: -1
total-routes: 1000
total-services: 100
paid-service-plans-allowed: false
enable-remove-users: true
