org: ds
space: ops_utilities-concourse
space-developer:
  ldap_users: []
  users:
  - admin  
  - adam.mott@csaa.com
  - kcampos
  - jdee
  - pbardzinski
  - lita-concourse
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - jdee
  - pbardzinski
  - lita-concourse
  - admin
  - adam.mott@csaa.com
  - kcampos
  ldap_group: ""
space-auditor:
  ldap_users: []
  users:
  - lita-concourse
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
