org: ds
space: claims-rideshare-dev
space-developer:
  ldap_users: []
  users:
  - ci-rideshare
  - vikram.ravindhran@csaa.com
  - amit.mishra@csaa.com
  - vasanth.jayaraman@csaa.com
  ldap_group: ""
space-manager:
  ldap_users: []
  users:
  - vikram.ravindhran@csaa.com
  - amit.mishra@csaa.com
  ldap_group: ""
space-auditor:
  ldap_users: []
  users: []
  ldap_group: ""
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
